wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712845667.0
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 2
      - 7
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: Model Fit Plot._type
      5: 1
      6:
      - 1
    - 1: Model Fit Plot.sha256
      5: 1
      6:
      - 1
    - 1: Model Fit Plot.size
      5: 1
      6:
      - 1
    - 1: Model Fit Plot.path
      5: 1
      6:
      - 1
    - 1: Model Fit Plot.format
      5: 1
      6:
      - 1
    - 1: Model Fit Plot.width
      5: 1
      6:
      - 1
    - 1: Model Fit Plot.height
      5: 1
      6:
      - 1
