wandb_version: 1

dataset:
  desc: null
  value: The Coca-Cola Company closing prices
architecture:
  desc: null
  value: 'RNN '
num_units:
  desc: null
  value: 40
num_layers:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0
seq_length:
  desc: null
  value: 13
start_date:
  desc: null
  value: '2009-01-01'
end_date:
  desc: null
  value: '2024-01-01'
epochs:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712754023.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
