wandb_version: 1

dataset:
  desc: null
  value: The Coca-Cola Company closing prices
architecture:
  desc: null
  value: RNN
num_units:
  desc: null
  value: 40
num_layers:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0
seq_length:
  desc: null
  value: 13
start_date:
  desc: null
  value: '2009-01-01'
end_date:
  desc: null
  value: '2024-01-01'
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713383206.0
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
