wandb_version: 1

dataset:
  desc: null
  value: The Coca-Cola Company closing prices
architecture:
  desc: null
  value: RNN
num_units:
  desc: null
  value: 40
num_layers:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0
seq_length:
  desc: null
  value: 13
start_date:
  desc: null
  value: '2009-01-01'
end_date:
  desc: null
  value: '2024-01-01'
epochs:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713085089.0
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      3:
      - 2
      - 7
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals._type
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals.sha256
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals.size
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals.path
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals.format
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals.width
      5: 1
      6:
      - 1
    - 1: Predictions vs Actuals.height
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
