wandb_version: 1

dataset:
  desc: null
  value: The Coca-Cola Company closing prices
architecture:
  desc: null
  value: LSTM
num_units:
  desc: null
  value: 50
num_layers:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0
seq_length:
  desc: null
  value: 11
start_date:
  desc: null
  value: '2003-01-01'
end_date:
  desc: null
  value: '2024-01-01'
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713856633.0
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      3:
      - 2
      - 7
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction._type
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction.sha256
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction.size
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction.path
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction.format
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction.width
      5: 1
      6:
      - 1
    - 1: Stock Price Prediction.height
      5: 1
      6:
      - 1
    - 1: metrics._type
      5: 1
      6:
      - 1
    - 1: metrics.sha256
      5: 1
      6:
      - 1
    - 1: metrics.size
      5: 1
      6:
      - 1
    - 1: metrics.artifact_path
      5: 1
      6:
      - 1
    - 1: metrics._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: metrics.path
      5: 1
      6:
      - 1
    - 1: metrics.ncols
      5: 1
      6:
      - 1
    - 1: metrics.nrows
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
